Repository footgrammer/todomodu_app, pull requests merged in 2025-06, with the labels that each got.

#62 [Project] 프로젝트 추가하기 및 프로젝트 불러오기
  lib/features/ai/data/datasources/openai_data_source_impl.dart
  lib/features/ai/data/models/openai_response_dto.dart
  lib/features/ai/domain/models/openai_response.dart
  lib/features/ai/presentation/pages/project_create_test_page.dart
  lib/features/notice/data/repositories/notice_repository_impl.dart
  lib/features/project/application/usecases/create_project_usecase.dart
  lib/features/project/data/datasources/project_data_source.dart
  lib/features/project/data/datasources/project_data_source_impl.dart
  lib/features/project/data/models/project_dto.dart
  lib/features/project/data/repositories/project_repository.dart
  lib/features/project/data/repositories/project_repository_impl.dart
  lib/features/project/domain/repositories/project_repository.dart
  lib/features/project/domain/usecases/create_project_usecase.dart
  lib/features/project/domain/usecases/fetch_projects_by_user_id_usecase.dart
  lib/features/project/presentation/models/project_create_state.dart
  lib/features/project/presentation/pages/project_create_page.dart
  lib/features/project/presentation/pages/project_create_subtask_page.dart
  lib/features/project/presentation/pages/project_create_todo_page.dart
  lib/features/project/presentation/pages/project_list_page.dart
  lib/features/project/presentation/pages/project_loading_page.dart
  lib/features/project/presentation/providers/project_providers.dart
  lib/features/project/presentation/viewmodels/project_create_view_model.dart
  lib/features/project/presentation/viewmodels/project_list_view_model.dart
  lib/features/project/presentation/viewmodels/project_loading_view_model.dart
  lib/features/project/presentation/widgets/project/project_card_list.dart
  lib/features/project/presentation/widgets/project_create/project_todo_list.dart
  lib/features/todo/data/models/subtask_dto.dart
  lib/features/todo/data/repositories/todo_repository_impl.dart
  lib/features/user/presentation/viewmodels/user_view_model.dart
  lib/main.dart
  lib/shared/utils/log_if_debug.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#99 [todo_detail_page] 할 일 삭제시 관련 세부 할 일들 삭제되지 않는 버그 해결
  lib/features/todo/data/repositories/subtask_repository_impl.dart
  lib/features/todo/data/repositories/todo_repository_impl.dart
  lib/features/todo/domain/repositories/subtask_repository.dart
Labels: fix

#109 [add/edit_todo_page] 바텀시트 내부 확인 버튼 누르면 폼 전체가 제출되는 버그 수정
  lib/features/todo/presentation/widgets/member_search_input.dart
  lib/features/todo/presentation/widgets/subtask/subtask_item.dart
  lib/features/todo/presentation/widgets/user_search_bottom_sheet.dart
  pubspec.lock
Labels: fix

#111 [project] 프로젝트 추가하기 에러 수정 및 프로젝트 카드 변경
  lib/app/todomodu_app.dart
  lib/features/project/data/datasources/project_data_source.dart
  lib/features/project/data/datasources/project_data_source_impl.dart
  lib/features/project/data/repositories/project_repository_impl.dart
  lib/features/project/domain/repositories/project_repository.dart
  lib/features/project/domain/usecases/add_member_to_project_usecase.dart
  lib/features/project/domain/usecases/delete_project_usecase.dart
  lib/features/project/domain/usecases/get_project_by_invitation_code_usecase.dart
  lib/features/project/presentation/models/project_create_state.dart
  lib/features/project/presentation/models/project_list_state.dart
  lib/features/project/presentation/pages/project_create_page.dart
  lib/features/project/presentation/pages/project_create_subtask_page.dart
  lib/features/project/presentation/pages/project_create_todo_page.dart
  lib/features/project/presentation/pages/project_detail_page.dart
  lib/features/project/presentation/pages/project_detail_popup_menu.dart
  lib/features/project/presentation/pages/project_loading_page.dart
  lib/features/project/presentation/providers/project_providers.dart
  lib/features/project/presentation/viewmodels/project_create_view_model.dart
  lib/features/project/presentation/viewmodels/project_list_view_model.dart
  lib/features/project/presentation/viewmodels/project_loading_view_model.dart
  lib/features/project/presentation/widgets/project/empty_project.dart
  lib/features/project/presentation/widgets/project/member_icon.dart
  lib/features/project/presentation/widgets/project/project_card.dart
  lib/features/project/presentation/widgets/project/project_card_list.dart
  lib/features/project/presentation/widgets/project/project_member_icons.dart
  lib/features/project/presentation/widgets/project/project_progress_bar.dart
  lib/features/project/presentation/widgets/project/project_search_bar.dart
  lib/features/project/presentation/widgets/project_create/project_subtask_list.dart
  lib/features/project/presentation/widgets/project_create/project_todo_list.dart
  lib/features/project/presentation/widgets/project_create/project_todo_subtask_list.dart
  lib/features/project/presentation/widgets/project_detail/project_member_section.dart
  lib/features/user/data/datasources/user_data_source.dart
  lib/features/user/data/datasources/user_data_source_impl.dart
  lib/features/user/data/repositories/user_repository_impl.dart
  lib/features/user/domain/repositories/user_repository.dart
  lib/main.dart
  lib/shared/utils/date_utils.dart
  lib/shared/widgets/custom_yes_or_no_dialog.dart
  pubspec.lock
Labels: feat

#116 [notice create page] 키보드 올라올 때 완료 버튼도 같이 올라오게 표시
  lib/features/notice/presentation/pages/notice_create_page.dart
Labels: design
